language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  - bower_components
node_js:
- 0.10
install:
- npm install -g bower
- npm install -g coffee-script
- npm install
- npm install jasmine-core --save-dev
- bower install
before_script:
- node_modules/.bin/brunch build
- cp -r public public-test
- node_modules/.bin/brunch build -P
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
script: node_modules/karma/bin/karma start test/karma.travis.conf.js
deploy:
- provider: s3
  access_key_id:
    secure: e87g5a0gpoz1zMmIMHC9El0m0y1LXLiTETXT8s7aCa5VZwKYofMHOGt2xkc/uoZQo2l4E8AQCzJRlWRIa1DvrtM2B7y6NKBhL8hQvaLcRR+sW2KzFXnn2yDRbDyNlLW2/GHRd2270/gyaJ/iFk/QKQaagm8+j2+ielj9ktZqvuE=
  secret_access_key:
    secure: Cy/pibLvLHbtmEoDZ1Jor8P26DAaZhnbqe32UtfRTW35HWbVIJVqf9/tHQFEViShsamIhRD3WAXyZH5zv+tUV/Adc17MSuIiQSb3RP+8IwX79/JVK628X4pIAP2daFDmXu/25t0ynvCiag6Vf9/J2R+NhDJ5hqdmSU1imHT1nb0=
  bucket: models-resources
  local-dir: public
  upload-dir: "biologica-ui"
  skip_cleanup: true
  on:
    repo: concord-consortium/biologica-ui
    branch: production
- provider: s3
  access_key_id:
    secure: e87g5a0gpoz1zMmIMHC9El0m0y1LXLiTETXT8s7aCa5VZwKYofMHOGt2xkc/uoZQo2l4E8AQCzJRlWRIa1DvrtM2B7y6NKBhL8hQvaLcRR+sW2KzFXnn2yDRbDyNlLW2/GHRd2270/gyaJ/iFk/QKQaagm8+j2+ielj9ktZqvuE=
  secret_access_key:
    secure: Cy/pibLvLHbtmEoDZ1Jor8P26DAaZhnbqe32UtfRTW35HWbVIJVqf9/tHQFEViShsamIhRD3WAXyZH5zv+tUV/Adc17MSuIiQSb3RP+8IwX79/JVK628X4pIAP2daFDmXu/25t0ynvCiag6Vf9/J2R+NhDJ5hqdmSU1imHT1nb0=
  bucket: models-resources
  local-dir: public
  upload-dir: "biologica-ui-dev"
  skip_cleanup: true
  on:
    repo: concord-consortium/biologica-ui
    branch: master
